config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  get 'welcome/index'

  resources :docs

  authenticated :user do
    root 'docs#index', as: 'authenticated_root'
  end

  root 'welcome#index'





end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/doc.rb
class Doc < ApplicationRecord
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :docs
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/docs_controller.rb
class DocsController < ApplicationController

  before_action :find_doc, only: [:show, :edit, :update, :destroy]

  def index
    @docs = Doc.where(user_id: current_user)
  end

  def show
    #@doc = Doc.find(params[:id])
  end

  def new
    @doc = current_user.docs.build
  end

  def create

    @doc = current_user.docs.build(doc_params)

    if @doc.save
      redirect_to @doc
    else
      render 'new'
    end

  end

  def edit
    #@doc = Doc.find(params[:id])
  end

  def update

    #@doc = Doc.find(params[:id])

    if @doc.update(doc_params)
      redirect_to @doc
    else
      render 'edit'
    end
  end

  def destroy
    #@doc = Doc.find(params[:id])
    @doc.destroy
    redirect_to docs_path
  end



  private

    def find_doc
      @doc = Doc.find(params[:id])
    end

    def doc_params
      params.require(:doc).permit(:title, :content)
    end

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/docs_helper.rb
module DocsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/docs/_form.html.haml
= simple_form_for @doc do |f|
    = f.input :title
    = f.input :content
    = f.button :submit

app/views/docs/edit.html.haml
%h1 Fix Doc!

= render 'form'
= link_to 'Cancel', doc_path

app/views/docs/index.html.haml
- @docs.each do |doc|
  %h2= link_to doc.title, doc
  %p= time_ago_in_words(doc.created_at)
  %p= truncate(doc.content, length: 50)

= link_to 'Create Doc', new_doc_path

app/views/docs/new.html.haml
%h1 New Doc!

= render 'form'

app/views/docs/show.html.haml
-# %h1 Debug Output
-# %p Document ID: #{@doc&.id}
-# %p Document Title: #{@doc&.title}
-# %p Document Content: #{@doc&.content}



%head
= csrf_meta_tag
= javascript_include_tag 'application'
= javascript_include_tag 'someScript', type: "module"

%h1 #{@doc&.title}
%p #{@doc&.content}

= link_to "All Docs", docs_path
= link_to "Fix Doc", edit_doc_path(@doc)
= link_to "Trash it", doc_path(@doc), method: :delete, data: { confirm: "Are you sure?" }

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Cabinet</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= javascript_importmap_tags %>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>

    <%= javascript_include_tag 'application', crossorigin: 'anonymous', 'data-turbolinks-track': 'reload' %>

  </head>

  <body>

    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>

    <%= yield %>

  </body>
</html>

app/views/welcome/index.html.haml
%h1 Voila! This is placeholder!